### PR TITLE
Use module-wide logger instead of root logger.

### PR DESCRIPTION
**Pull request by jaepil**
Using root logger can generate verbose log messages for application wide. Also, it makes things hard when you need to change the log level for a particular module. This PR fixes this issue by using module-wide child logger instead of root logger.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for this PR. I haven't used or worked on this library for quite a while.

This PR looks good enough for a merge, but I'm not set up to test anything pdfminer-related anymore.

Would you be interested in assuming maintainership of this library?

**Comment by jaepil** [comment]
I'm interested in maintaining this library. It would be great if I can contribute to this project.

Thanks,

**Comment by ghost** [comment]
Cool. So here's what I propose: I transfer the ownership of this repo to you as well as ownership of the PyPI package. Is that ok for you? Do you have a PyPI account?

**Comment by jaepil** [comment]
Sounds great. My PyPI account is `jaepil`. Look forward to work on this project!

**Comment by ghost** [comment]
Ownership transfer failed on github because the repo already exists in your namespace. You will need to delete or rename your fork before I can proceed.

**Comment by jaepil** [comment]
Oh, I changed the repository name on my side.

**Comment by ghost** [comment]
Sorry, I thought renaming would be enough, but I think that deleting it will be necessary. The error message I get is now "jaepil already has a repository in the euske/pdfminer network"

**Comment by jaepil** [comment]
No problem. I deleted it from my account.

Thanks,

**Comment by ghost** [comment]
Done. You also have PyPI ownership. have fun!

**Comment by jaepil** [comment]
Thanks!

**Pull request merged**
